debuginfo: handle multiple calls to drgn_prog_set()
On an internal analysis system, drgn_prog_set() was called multiple
times, resulting in the following error on startup (debug logging
enabled for illustration):

debug:drgn.plugins: loaded entry point 'oracle = drgn_tools.debuginfo'
debug:drgn.plugins: loaded entry point 'oracle = drgn_tools.debuginfo'
warning:drgn.plugins: 'oracle' drgn_prog_set failed:
Traceback (most recent call last):
  File "/share/linuxtools/dev/drgn_venv_ol9/lib64/python3.9/site-packages/_drgn_util/plugins.py", line 139, in call_plugins
    hook(*args)
  File "/share/linuxtools/dev/drgn_venv_ol9/lib64/python3.9/site-packages/drgn_tools/debuginfo.py", line 818, in drgn_prog_set
    prog.register_debug_info_finder(
ValueError: duplicate module debug info finder name 'ol-vmlinux-repo'

The root cause is that importlib lists our plugin twice on this system.
I'm not sure why -- it may be due to an issue with the installation.
While that also needs to be fixed, we should still be able to handle
duplicate calls without an error, so add a defensive check.

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>